### ISSUE TITLE
add files to Vault

### ISSUE THREAD

**Issue by koechlm** [koechlm/iLogic-Vault#13]
as an iLogic user, I need to create export file formats, like IFC, STP, or any other type, and add them to Vault. iLogic-Vault methods do not include a method to add new files.
Sample: dim success as bool = iLogicVault.AddFile(oExportFullFilePath).

**Comment by Caddylad** [comment]
Hi Markus, I was just wondering if you could advise, I am currently working on some automation for the products that our company produce and would be interested in a sample code if possible to implement the add files to vault as we have a few exports that it would be good to automate checking in to vault, I tried the above sample but it didn't work, but that may just be because I am fairly new to the coding side, at least the advanced side anyway.

Thank you in advance

K

**Comment by koechlm** [comment]
@Caddylad: branch 2021.1.0 already includes the add file function. I did not compile a release yet and planned to do it by end of March. For now, you would need to compile the latest commit of the mentioned branch on your own.
